In [1]:
import numpy as np

In [2]:
myArr = np.array([[3,6,32,7]], np.int32)

In [3]:
myArr

array([[ 3,  6, 32,  7]])

In [4]:
myArr[0,1]

6

In [5]:
myArr.shape

(1, 4)

In [6]:
myArr.dtype

dtype('int32')

# Array Creation: Conversion from other python other data structures

In [7]:
listArray = np.array([[1,2,3],[5,6,7],[8,9,10]])

In [8]:
listArray

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [9]:
listArray.dtype

dtype('int32')

In [10]:
listArray.shape

(3, 3)

In [11]:
listArray.size

9

In [12]:
#creates an array of size mxn filled with zeros
zeros = np.zeros((2,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros.dtype

dtype('float64')

In [15]:
zeros.shape

(2, 5)

In [16]:
#Creates an array of size n from 0 to n-1
rng = np.arange(10)

In [17]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#Creates an array where first value is p(1 in this case) last value is q(5 in this case) 
#and there are r(10 in this case) equally sapced elements in this range
lspace = np.linspace(1,5,10)

In [19]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [20]:
#Creates an empty array of size mxn filled with random values
emp = np.empty((4,6))

In [21]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.69118787e-306, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 8.90104239e-307, 6.89804132e-307,
        9.34605716e-307, 1.37962456e-306, 1.42418172e-306],
       [2.04712906e-306, 7.56589622e-307, 1.11258277e-307,
        8.90111708e-307, 2.11389826e-307, 1.11260619e-306]])

In [22]:
#Creates a copy of array passed 
emp_like = np.empty_like(lspace)

In [23]:
emp_like

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
#Creates a nxn identity matrix
I = np.identity(3)

In [25]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
#reshape such that m*n == og no of elements
arr = arr.reshape(3,33)

In [28]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
#Converts to 1D array
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
x = ([[1,2,3],[4,5,6],[7,1,0]])

In [31]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [32]:
ar.sum(axis=0)

array([12,  8,  9])

In [33]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [34]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [35]:
for item in ar.flat:
    print(item,end=" ")

1 2 3 4 5 6 7 1 0 

In [36]:
ar.ndim

2

In [37]:
ar.nbytes

36

In [38]:
one = np.array([1,3,4,634,2])

In [39]:
#Returns position of maximum element
one.argmax()

3

In [40]:
#Returns position of minimum element
one.argmin()

0

In [41]:
#Returns indexes of elements in sorted order
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [42]:
#In this case it converts 2D array into 1D array and returns index of min/max accordingly 
print(ar.argmin())
print(ar.argmax())

8
6


In [43]:
#Returns index of max val in column
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [44]:
#Returns index of min val in column
ar.argmin(axis=0)

array([0, 2, 2], dtype=int64)

In [45]:
#Returns index of max val in row
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [46]:
#Returns index of min val in row
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [47]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [48]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

# Mathematical operations

In [49]:
ar2 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [52]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [53]:
#Multiplies element wise
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [54]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [55]:
a2 = np.array([[1,4,9],[16,25,36],[49,64,81]])
np.sqrt(a2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [56]:
ar2.sum()

23

In [57]:
a2.max()

81

In [58]:
a2.min()

1

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [5]:
y = np.arange(8)
y

array([0, 1, 2, 3, 4, 5, 6, 7])

array([[0, 1],
       [2, 3]])

In [2]:
cpx = 2 + 1j
print(cpx.conjugate)

NameError: name 'j1' is not defined